Resolving error & adding safegaurds to qatest.yaml
Resolving following error:
Run BUILD_ID=13273125546
BUILD_ID=13273125546 : The term 'BUILD_ID=13273125546' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\actions-runner\_work\_temp\8f7d95ba-16d4-4e61-86ab-ea5621798eb4.ps1:2 char:1
+ BUILD_ID=13273125546
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (BUILD_ID=13273125546:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Error: Process completed with exit code 1.

- shell: pwsh provided for some steps to ensure use of PowerShell Core
- Replaced curl with Invoke-WebRequest
- Safer path handling: Uses $env:TEMP\secondlife-build-$BUILD_ID instead of ~
- / replaced with \ in directories
- Removes unnecessary powershell -Command "& { ... }"