Disable warning due to unused _out.
The intent of that LL_DEBUGS seems unclear. I'd wager it does not log anything at all

error: statement has no effect [-Werror=unused-value]
  387 |                         _out
      |                         ^~~~
note: in expansion of macro ‘lllog_test_’
  381 |                 lllog_test_()
      |                 ^~~~~~~~~~~
note: in expansion of macro ‘lllog’
  429 | #define LL_DEBUGS(...)  lllog(LLError::LEVEL_DEBUG, false, ##__VA_ARGS__)
      |                         ^~~~~
note: in expansion of macro ‘LL_DEBUGS’
  830 |         LL_DEBUGS("LogViewerStatsPacket");
      |         ^~~~~~~~~