Resolving QA workflow error
Error:
At C:\actions-runner\_work\_temp\75a52fce-ed9c-4350-9d42-831b85733476.ps1:9 char:3
+ if [[ -z "$ARTIFACT_NAME" ]]; then
+   ~
Missing '(' after 'if' in if statement.
At C:\actions-runner\_work\_temp\75a52fce-ed9c-4350-9d42-831b85733476.ps1:9 char:5
+ if [[ -z "$ARTIFACT_NAME" ]]; then
+     ~
Missing type name after '['.
At C:\actions-runner\_work\_temp\75a52fce-ed9c-4350-9d42-831b85733476.ps1:21 char:3
+ if [[ ! -f ~/secondlife-build/installer.zip ]]; then
+   ~
Missing '(' after 'if' in if statement.
At C:\actions-runner\_work\_temp\75a52fce-ed9c-4350-9d42-831b85733476.ps1:21 char:5
+ if [[ ! -f ~/secondlife-build/installer.zip ]]; then
+     ~
Missing type name after '['.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 
Error: Process completed with exit code 1.