Chore/cmake pretty up (#1205)
* - Add an option to with ASAN
- Fix GCC -Werror option.

* - find_program should not set REQUIRED if per logic a fallback to ld.bfd is fine
- cmake idiomatic is to test Variables without dereferencing  them

* Add -Wno-unknown-warning-option for clang or it will complain about some GCC only options

```
/home/runner/work/viewer/viewer/indra/llcommon/llsdutil.cpp:39:32: error: unknown warning group '-Wstringop-truncation', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wstringop-truncation" // It's actually okay what happens here
```